server:
  port: 9502

spring:
  application:
    name: spring-boot-mongodb
  data:
    mongodb:
#      host: 106.14.200.2
#      port: 27018
#      database: usdt
#      username: gikee
#      password: gikee_data_service
#      authentication-database: admin
      address: 47.100.15.84:27018
      database: test

  ## Redis config
  redis:
    host: 139.196.100.85
    port: 6379
    password: gikee_redis
    database: 0
    timeout: 20000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 8
        max-wait: -1
    channel: TxChangeInfoTest

  kafka:
    bootstrap-servers: gikee103:9092,gikee104:9092,gikee105:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      batch-size: 8192
      buffer-memory: 20480
    blockTopic: USTD_BLOCK_TEST
    transactionTopic: USTD_TRANSACTION_TEST

## websocket
websocket:
  url: ws://139.196.100.85:60080/bigChange

## usdt config
usdt:
  username: gikee
  password: 123456
  clientAddress: http://192.168.0.168:8383