server:
  port: 9502

spring:
  data:
    mongodb:
      address: 106.14.200.2:27018
      database: usdt
      username: gikee
      password: gikee_data_service
      authentication-database: admin

  #  application:
  #    name: spring-boot-mongodb
  #  data:
  #    mongodb:
  #      host: 106.14.200.2
  #      port: 27018
  #      database: usdt
  #      username: gikee
  #      password: gikee_data_service
  #      authentication-database: admin

  ## Redis config
  redis:
    host: 139.196.100.85
    port: 6379
    password: gikee_redis
    database: 0
    timeout: 100000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    channel: TxChangeInfo

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      batch-size: 8192
      buffer-memory: 20480
      bootstrap-servers: 47.103.77.104:9991,47.103.77.104:9992,47.103.77.104:9993
    blockTopic: USTD_BLOCK
    transactionTopic: USTD_TRANSACTION

## websocket
websocket:
  ##url: ws://139.196.100.85:60080/bigChange
  url: ws://192.168.1.122:60080/bigChange/usdt

## usdt config
usdt:
  username: gikee
  password: 123456
  clientAddress: http://192.168.0.168:8383